### PR TITLE
Add FUNDING

### PR DESCRIPTION
**Pull request by krafit**
This file will add a "Sponsor" Button to all of our projects as it's already the case in the [Antispam Bee repo](https://github.com/pluginkollektiv/antispam-bee/) today.

Currently we only support PayPal, but if we should expand to other donation services in the future, we could easily add them to this list. 

See [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) for further details regarding the sponsor button.

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]
LGTM!

**Comment by florianbrinkmann** [comment]
If I understand the documentation right

>custom: LINK1 or custom: [LINK1, LINK2, LINK3, LINK4]

that would add two links to the list (one to the paypal.com donation form and one to paypal.com), or am I missing something?

**Comment by pfefferle** [comment]
Oh yes, you are Right!

**Comment by pfefferle** [comment]
https://github.com/pluginkollektiv/.github/pull/4

**Review by bueltge — APPROVED** [review]
With #4 is fine.

**Pull request merged**
